### ISSUE TITLE
1.3 release / 1.3.1 dev Bugs

### ISSUE THREAD

**Issue by NlL5** [mchorse/blockbuster#15]
I tested these bugs in 1.3 and then retested them in the latest dev commit to check if they're still existing.

- [x] The director block doesn't update Actors when pressing 'Done'.
- [x] Changes done with the Actor configuration tool don't get adopted by the director block. (The Actors model, skin and visibility setting get reset when starting the playback of the director block.)
- [x] Detaching an Actor doesn't completely detach him. When you right-click a detached Actor, the playback of the previously attached director block will be started.
- [x] When recording an Actor, the POV of the player gets changed, and the Bounding Box as well, at least on client side. But it seems that the server doesn't get updated. What I mean is that one cannot record chickens walking through a 1-block hole.
- [x] Similar with the Bounding Box of Actors: They get changed on the client side when changing the model. But when a chicken-Actor is standing beneath a 1-block whole, the Actor suffocates in the wall.
- [x] Invisible Actors still have shadows :-S
- [x] ~~Playback of registering Registration tool crashes the game. (Recursive use of blockbuster.)~~ _*Stacktrace_ below. Steps to reproduce:<br>
° Start recording<br>
° Place a director block (While recording!)<br>
° Take a Registration Tool and right-click the director block<br>
° Stop recording<br>
° Play back the action.<br>
_I know, this is a mean test_ :wink: _(I didn't test other blockbuster functions.)_
- [x] ~~If 1 Actor is attached to 2 director blocks, only the latest attached director block starts playback when recording the Actor. _I expected that 1 Actor can only be attached to 1 director block_~~ (scheduled to #13)

## Added by @mchorse

- [x] Make `alex` and `steve` arms idling

<br>
> **Bugs only in the dev version:**
> - Playback of a detached Actor doesn't work properly. On playback sometimes an Actor spawns, that doesn't play it's playback file, but sometimes no Actor spawns.
> - `/action play <file>` doesn't start the playback. It surely has something to do with the above error that spawns no actor.

<br>
_* Stacktrace for 1.3.1 dev version:_
`java.lang.ClassCastException: mchorse.blockbuster.common.entity.EntityActor$1 cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at mchorse.blockbuster.common.block.BlockDirector.displayCast(BlockDirector.java:66)
	at mchorse.blockbuster.common.block.AbstractBlockDirector.func_180639_a(AbstractBlockDirector.java:123)
	at mchorse.blockbuster.recording.actions.InteractBlockAction.apply(InteractBlockAction.java:51)
	at mchorse.blockbuster.recording.data.Record.applyAction(Record.java:74)
	at mchorse.blockbuster.recording.RecordPlayer.next(RecordPlayer.java:47)
	at mchorse.blockbuster.common.entity.EntityActor.func_70636_d(EntityActor.java:210)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2020)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by NlL5** [comment]
I'll continue searching tomorrow or so :wink:

**Comment by mchorse** [comment]
> Detaching an Actor doesn't completely detach him. When you right-click a detached Actor, the playback of the previously attached director block will be started.

Oh, yeah, I forgot about that. I think I'll fix that in this patch. 

> Invisible Actors still have shadows :-S

Dang :disappointed: 

> If 1 Actor is attached to 2 director blocks, only the latest attached director block starts playback when recording the Actor. I expected that 1 Actor can only be attached to 1 director block

That's going to be scheduled on 1.3.2

> When recording an Actor, the POV of the player gets changed, and the Bounding Box as well, at least on client side. But it seems that the server doesn't get updated. What I mean is that one cannot record chickens walking through a 1-block hole.

Hm, it should be... Is it on intergrated server or on dedicated server? To check AABB you can use `F3 + B` keybinding.

> Playback of registering Registration tool crashes the game. (Recursive use of blockbuster.)

Not really sure how to deal with it. I will probably blacklist director block for interaction, by the way, for now, don't try interacting with chest while recording :laughing: 

> Playback of a detached Actor doesn't work properly. On playback sometimes an Actor spawns, that doesn't play it's playback file, but sometimes no Actor spawns.

I think that related to the new recording system. I didn't completely tested it. The problem, I think, is that a desync happens when playback starts, that's probably result into corrupted data or no data at all on the client side (client side is responsible for playbacking the actor's position, rotation, etc.).

I'll look into that later.

> /action play <file> doesn't start the playback. It surely has something to do with the above error that spawns no actor.

Probably...

Thanks for the report :smile: :+1:

**Comment by NlL5** [comment]
Sorry for late reply.

> Hm, it should be... Is it on intergrated server or on dedicated server? To check AABB you can use F3 + B keybinding.
Yeah I checked that. It's on integrated server. And the AABB was displayed correctly as one would expect. Here's a video: https://youtu.be/mcZNkm1YJQs
Btw, <sup>Similar with the Bounding Box of Actors: They get changed on the client side when changing the model. But when a chicken-Actor is standing beneath a 1-block whole, the Actor suffocates in the wall.</sup> is now fixed! Now the Actor seems to have the correct AABB while playback! (But he still can suffocate in a wall, when he is. But that's completely correct! https://youtu.be/y2SxIUCyNc8)

> Not really sure how to deal with it. I will probably blacklist director block for interaction, by the way, for now, don't try interacting with chest while recording :laughing:
I won't :smile: Yeah, I think blacklisting is reasonable.

> Thanks for the report :smile: :+1: 
You're welcome :wink:

**Comment by mchorse** [comment]
@NlL5 are these issues are still relevant or not:

> When recording an Actor, the POV of the player gets changed, and the Bounding Box as well, at least on client side. But it seems that the server doesn't get updated. What I mean is that one cannot record chickens walking through a 1-block hole.
> 
> Similar with the Bounding Box of Actors: They get changed on the client side when changing the model. But when a chicken-Actor is standing beneath a 1-block whole, the Actor suffocates in the wall.

I'm confused a little bit 😕

**Comment by mchorse** [comment]
Sorry for disturbing, I actually found out the problem. I sent the morph to the client, but forgot to set it on the server 😆

However, I cannot reproduce the same thing for the second one (actors). Could you explain how to do that?

**Comment by NlL5** [comment]
The second one is already fixed! Did you get my message?
https://github.com/mchorse/blockbuster/issues/15#issuecomment-254352099
I wanted to point out that it's fixed xD

**Comment by mchorse** [comment]
@NlL5 yes, I did get the message, however I was confused if it's fixed or not :laughing:

**Comment by NlL5** [comment]
ohhhh ok! xD
